# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir pandas httpx mcp[cli] pydantic python-dotenv

# Set environment variables placeholders (they will be overridden by startCommand config)
ENV KO_WEATHER_API_KEY=your_api_key_here

# Command to run the MCP server
CMD ["python", "src/server.py"]
