# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copy all project files into the container
COPY . .

# Install dependencies from requirements.txt and openpyxl for Excel support
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir openpyxl

# Run database migration to prepare SQLite database from Excel
RUN python src/migrate.py

# Start the MCP server
CMD ["python", "src/server.py"]
