[project]
name = "py-mcp-ko-weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "openpyxl",
    "requests",
    "python-dotenv",
    "pydantic",
]
